apiVersion: v2
name: eo-auth
description: A Helm chart for Kubernetes

type: application
version: 0.2.16

dependencies:
  - name: eo-base-helm-chart
    version: "v0.6.2"
    repository: "https://energinet-datahub.github.io/helm-charts/"
  - name: postgresql
    version: "11.6.6"
    repository: "https://charts.bitnami.com/bitnami"
