---
publicIngress:
  paths:
    - /api/auth/oidc/login
    - /api/auth/terms
    - /api/auth/terms/accept
  middlewares:
    - name: auth-stripprefix

fullnameOverride: "eo-auth"

eo-base-helm-chart:
  fullnameOverride: "eo-auth"

  env:
    TOKEN_COOKIE_SAMESITE: true
    PSQL_HOST: eo-auth-postgresql
    PSQL_PORT: 5432
    PSQL_USER: postgres2
    PSQL_DB: auth
    SQL_POOL_SIZE: 1
    # TODO Delete line below
    # PSQL_PASSWORD: testpassword
  podSpec: {}

  envSecrets:
    INTERNAL_TOKEN_SECRET:
      secretName: auth-random-secret
      key: eo-token-secret

    STATE_ENCRYPTION_SECRET:
      secretName: auth-random-secret
      key: eo-state-encryption-secret

    # TODO Uncomment this below
    # PSQL_PASSWORD:
    #   secretName: auth-postgres-secret
    #   key: postgres-password

    PSQL_PASSWORD:
      secretName: auth-postgres-secret
      key: postgresql-password

  deployments:
    api:
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_api.sh"
      probes: true
      env: {}
      image:
        repository: ghcr.io/energinet-datahub/eo-auth-api
        tag: 0.2.16
  service:
    deployment: api
    type: ClusterIP
    port: 80

  ingress:
    hosts: []
    paths:
      - /api/auth
    pathExceptions:
      - /api/auth/oidc/login
      - /api/auth/terms
      - /api/auth/terms/accept
    servicePort: 80
    middlewares:
      - name: auth-stripprefix
      - name: eo-auth-service

  middleware:
    stripPrefix:
      name: auth-stripprefix
      prefixes:
        - /api/auth

# global:
#   postgresql:
#       auth:
#         username: postgres
#         database: auth
#         # TODO Remove line below
#         password: testpassword
#         # TODO Uncomment line below
#         # existingSecret: auth-postgres-secret

global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlDatabase: auth
    existingSecret: auth-postgres-secret
