publicIngress:
  paths:
    - /api/auth/oidc/login
  middlewares:
    - name: auth-stripprefix

fullnameOverride: "eo-auth"

eo-base-helm-chart:
  fullnameOverride: "eo-auth"

  env: {}
  podSpec: {}

  randomSecret:
    eo-random-secret:
      - eo-token-secret
      - eo-ssn-secret 

  envSecrets:
   INTERNAL_TOKEN_SECRET:
     secretName: eo-random-secret
     key: eo-token-secret
     
   SSN_ENCRYPTION_KEY:
     secretName: eo-random-secret
     key: eo-ssn-secret

  deployments:
    api: 
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_api.sh"
      probes: true
      env: {}
      image:
        repository: projectorigin/auth
        tag: "latest"
        pullPolicy: Always

  service:
    deployment: api
    type: ClusterIP
    port: 80
#    proxy:
#      host: "172.17.0.1"

  ingress:
    hosts: []
    paths:
      - /api/auth
    pathExceptions:
      - /api/auth/oidc/login
    servicePort: 80
    middlewares:
      - name: auth-stripprefix
      - name: eo-auth-service

  middleware:
    stripPrefix:
      name: auth-stripprefix
      prefixes:
        - /api/auth

global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: 1234
    postgresqlDatabase: auth
