eo-base-helm-chart:
  env: {}

  deployments:
    api: 
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_api.sh"
      probes: true
      env: {}
      image:
        repository: projectorigin/auth
        tag: "latest"
        pullPolicy: Always

  service:
    deployment: auth-api
    type: ClusterIP
    port: 9096
    proxy:
      host: "172.17.0.1"

  ingress:
    hosts: []
    paths:
      - /api/auth
    servicePort: 9096
    middlewares:
      - auth-stripprefix

  middleware:
    stripPrefix:
      name: auth-stripprefix
      prefixes:
        - /api/auth
