publicIngress:
  paths:
    - /api/auth/login
  middlewares:
    - auth-stripprefix

eo-base-helm-chart:
  env: {}

  deployments:
    api: 
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_api.sh"
      probes: true
      env: {}
      image:
        repository: projectorigin/auth
        tag: "latest"
        pullPolicy: Always

  service:
    deployment: auth-api
    type: ClusterIP
    port: 80
#    proxy:
#      host: "172.17.0.1"

  ingress:
    hosts: []
    paths:
      - /api/auth
    pathExceptions:
      - /api/auth/login
    servicePort: 80
    middlewares:
      - auth-stripprefix
      - eo-auth-service

  middleware:
    stripPrefix:
      name: auth-stripprefix
      prefixes:
        - /api/auth
