ett-base-helm-chart:
  env: {}

  deployments:
    - name: auth-api
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_api.sh"
      probes: true
      env: {}
      image:
        repository: projectorigin/ett-auth
        tag: "latest"
        pullPolicy: Always
    - name: auth-consumer
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_consumer.sh"
      probes: true
      env: {}
      image:
        repository: projectorigin/ett-auth
        tag: "latest"
        pullPolicy: Always

  service:
    deployment: auth-api
    type: ClusterIP
    port: 80
#    proxy:
#      host: "172.17.0.1"

  ingress:
    hosts: []
    paths:
      - /auth
    servicePort: 80
