
deployments:
  - name: auth-service
    replicaCount: 1
    image:
      repository: projectorigin/ett-auth
      tag: "latest"
      pullPolicy: Always

service:
  deployment: auth-service
  type: ClusterIP
  port: 80

ingress:
  host: localhost
  path: /auth
  servicePort: 80
