name: Build and push container

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Container image name
      id: image-name
      uses: ASzc/change-string-case-action@v2
      with:
        string: ghcr.io/${{ github.repository }}-api

    - name: Check github val
        run: | 
          echo ${{ github }}

    - name: Tag main
      id: tag-main
      if: github.event_name == 'pull_request'


    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.image-name.outputs.lowercase }}:pr-${{ github.event.pull_request.number }}-${{ github.run_number }}
