{{- if .Values.publicIngress }}

{{- $hosts := default .Values.eo-base-helm-chart.ingress.hosts .Values.publicIngress.hosts }}
{{- $middlewares := default .Values.eo-base-helm-chart.ingress.middlewares .Values.publicIngress.middlewares }}
{{- $httpMiddelwares := default .Values.eo-base-helm-chart.ingress.httpMiddelwares .Values.publicIngress.httpMiddelwares }}
{{- $tlsSecretName := default .Values.eo-base-helm-chart.ingress.tlsSecretName .Values.publicIngress.tlsSecretName }}

{{- $matchRules := list }}

{{- if $hosts }}
  {{- $hostsMatchRules := list }}
  {{- range $hosts }}
    {{- $hostsMatchRules = append $hostsMatchRules (printf "Host(`%s`)" . ) }}
  {{- end}}
  {{- $matchRules = append $matchRules (printf "(%s)" (join " || " $hostsMatchRules)) }}
{{- end}}

{{- if .Values.publicIngress.paths }}
  {{- $pathsMatchRules := list }}
  {{- range .Values.ingress.paths }}
    {{- $pathsMatchRules = append $pathsMatchRules (printf "PathPrefix(`%s`)" . ) }}
  {{- end}}
  {{- $matchRules = append $matchRules (printf "(%s)" (join " || " $pathsMatchRules)) }}
{{- end}}

{{- if .Values.publicIngress.pathExceptions }}
  {{- $invertedPathsMatchRules := list }}
  {{- range .Values.ingress.pathExceptions }}
    {{- $invertedPathsMatchRules = append $invertedPathsMatchRules (printf "PathPrefix(`%s`)" . ) }}
  {{- end}}
  {{- $matchRules = append $matchRules (printf "!(%s)" (join " || " $invertedPathsMatchRules)) }}
{{- end}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "eo-auth.fullname" . }}-http
  labels:
    {{- include "eo-auth.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
  - match: {{join " && " $matchRules}}
    kind: Rule
    services:
    - name: {{ include "eo-auth.fullname" . }}
      port: {{ .Values.eo-base-helm-chart.service.port }}
    {{- if (or $middlewares $httpMiddelwares) }}
    middlewares:
      {{- range $httpMiddelwares }}
      - name: {{ . }}
      {{- end }}
      {{- range $middlewares }}
      - name: {{ . }}
      {{- end }}
    {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "eo-auth.fullname" . }}-https
  labels:
    {{- include "eo-auth.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: {{join " && " $matchRules}}
    kind: Rule
    services:
    - name: {{ include "eo-auth.fullname" . }}
      port: {{ .Values.eo-base-helm-chart.service.port }}
    {{- if $middlewares }}
    middlewares:
      {{- range $middlewares }}
      - name: {{ . }}
      {{- end }}
    {{- end }}
    {{- if $tlsSecretName }}
    tls:
      secretName: {{ $tlsSecretName }}
    {{- end }}
{{- end }}
