apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ett-auth.fullname" . }}
  labels:
    {{- include "ett-auth.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: "ingress-traefik"
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "ett-auth.fullname" . }}
                port:
                  number: {{ .Values.ingress.servicePort }}
