apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ett-auth.fullname" . }}
  labels:
    {{- include "ett-auth.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
    kind: Rule
    services:
    - name: {{ include "ett-auth.fullname" . }}
      port: {{ .Values.ingress.servicePort }}
