apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: po-auth-service
  labels:
    {{- include "po-auth.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ include "po-auth.fullname" . }}.po.svc.cluster.local/auth
    authResponseHeaders:
      - Authorization
