apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: eo-auth-service
  labels:
    {{- include "eo-auth.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://eo-auth.{{ .Release.Namespace }}.svc.cluster.local:9096/token/forward-auth
    authResponseHeaders:
      - Authorization
