apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: eo-auth-service
  labels:
    {{- include "eo-auth.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ include "eo-auth.fullname" . }}.eo.svc.cluster.local/auth
    authResponseHeaders:
      - Authorization
