apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: eo-auth-service
  labels:
    {{- include "eo-auth.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://ett-auth-eo-base-helm-chart.{{ .Release.Namespace }}.svc.cluster.local/token/forward-auth
    authResponseHeaders:
      - Authorization
