apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oe-auth-service
  labels:
    {{- include "oe-auth.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ include "oe-auth.fullname" . }}.oe.svc.cluster.local/auth
    authResponseHeaders:
      - Authorization
