"""empty message

Revision ID: 7c454b8ab0d9
Revises: 9720f2c9aba2
Create Date: 2022-05-19 12:03:44.487536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c454b8ab0d9'
down_revision = '9720f2c9aba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tin', sa.String(), nullable=False),
    sa.CheckConstraint('tin != null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tin')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_tin'), 'company', ['tin'], unique=False)
    op.create_table('user_company',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.subject'], ),
    sa.PrimaryKeyConstraint('company_id', 'user_id'),
    sa.UniqueConstraint('company_id', 'user_id')
    )
    op.drop_index('ix_user_tin', table_name='user')
    op.drop_column('user', 'tin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_tin', 'user', ['tin'], unique=False)
    op.drop_table('user_company')
    op.drop_index(op.f('ix_company_tin'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
