name: Install dependencies

inputs:
  PYTHON_VERSION:
    description: 'The version of python to use'
    required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Get event val
        run: echo ${{ github.event.inputs.PYTHON_VERSION }}

      - name: Get input val
        run: echo ${{ inputs.PYTHON_VERSION }}

      - name: Set up Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev