name: Feature Release

on: 
  pull_request:
    branches: 
      - main

jobs:
  build_and_host_container:
    name: Build and host container
    runs-on: ubuntu-latest
    env:
      HOST_IMAGE_TAG: ${{ format('pr-{0}-{1}', github.event.pull_request.number, github.run_number) }}
    if:
      startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Container image name
        id: image-name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ghcr.io/${{ github.repository }}-api

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.image-name.outputs.lowercase }}:${{ env.HOST_IMAGE_TAG }}
