name: Helm Chart Version Check
on:
  pull_request:
    branches: [ main ]
jobs:
  check_version:
    uses: MartinSchmidt/ReusableWorkflow/.github/workflows/pr_helm_chart_version_check.yaml@main
    with:
      chart_folder: chart
