name: Orchestrator

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  py_validate:
    name: Validate python
    uses: Energinet-DataHub/.github/.github/workflows/python-pipenv-validate.yaml@main
    with:
      python_version: 3.8
      ignore_lint_error: true

  build_container_and_update_chart:
    name: Build containers
    needs: [py_validate]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arrays: [ 
          { deployment_name: "api", dockerfile: "Dockerfile" }
        ]
    steps:
      - uses: actions/checkout@v2

      - name: Update deployment in chart
        id: docker_build
        uses: Energinet-DataHub/.github/.github/actions/build-and-push-container@main
        with: 
          dockerfile: ${{ matrix.arrays.Dockerfile }}
          name: ${{ github.repository }}-${{ matrix.arrays.deployment_name }}

      - name: Update deployment in chart
        uses: Energinet-DataHub/.github/.github/actions/update-chart-deployment-image@main
        with: 
          deployment_name: ${{ matrix.arrays.deployment_name }}
          image: ${{ steps.docker_build.outputs.image_name}}
          tag: ${{ steps.docker_build.outputs.image_tag}}

  update_environment:
    name: Update env
    needs: [build_container_and_update_chart]
    uses: Energinet-DataHub/.github/.github/workflows/chart-release-and-update-env.yaml@main
    with:
      chart_folder: chart 
    secrets:
      RELEASE_CHART_TOKEN: ${{ secrets.RELEASE_CHART_TOKEN }}
      UPDATE_ENV_TOKEN: ${{ secrets.UPDATE_ENV_TOKEN }}
